language: ruby
rvm:
- 1.9.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
notifications:
  email:
  - mcivorsteiner@gmail.com
  - f.g.garbagnati@gmail.com
  - fatimakhalilova@gmail.com
  - kaelinbu@gmail.com
  - cyancey1@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: Q2/UfUAq70MJtG/K17S4wpC9g3jChX8qayd1PJxmr+brAOqrEreb+6vfM/WkxgtMlcwPV7kM/uQ/MpFKsILWgrt2EnFLl+QoPp7gOE4GO0OTvgDJMPz9viOAcWcipRfvHXddq2If+zqxdPO1vh0uLiGijsCjkdZf0s7VWebbpJ8=
  app: localbeat
  strategy: git
