language: ruby
cache: bundler
rvm:
- 1.9.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
notifications:
  email:
  - mcivorsteiner@gmail.com
  - f.g.garbagnati@gmail.com
  - fatimakhalilova@gmail.com
  - kaelinbu@gmail.com
  - cyancey1@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: YpO5UGPqHVSQ8p01rRAsO+eNnzYa5GOSUPrYODMjs4aSSVPlk5qeeMkcSVuRpayBGlQxbNoimQ0yPtSI/MZIzaFhUIOLQoLII9maA89umyJzSYTu2ztXoiJeu7zlegniT+CeEfZJBZ4QeEvFWd/NwtMm/T2mn97s5SLu96aNHRY=
  app: fathomless-mesa-2368
  strategy: git