language: ruby
cache: bundler
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
notifications:
  email:
    - mcivorsteiner@gmail.com
    - f.g.garbagnati@gmail.com
    - fatimakhalilova@gmail.com
    - kaelinbu@gmail.com
    - cyancey1@gmail.com